# config/routes.yml
macymedcacheboost_dashboard:
    path: /modules/macymedcacheboost/dashboard
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostDashboardController::index'
    methods: [GET]

macymedcacheboost_general:
    path: /modules/macymedcacheboost/general
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostGeneralController::index'
    methods: [GET, POST]

macymedcacheboost_bots:
    path: /modules/macymedcacheboost/bots
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostBotsController::index'
    methods: [GET, POST]

macymedcacheboost_assets: 
    path: /modules/macymedcacheboost/assets
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostAssetsController::index'
    methods: [GET, POST]

macymedcacheboost_pagetypes:
    path: /modules/macymedcacheboost/pagetypes
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostPageTypesController::index'
    methods: [GET, POST]

macymedcacheboost_redis:
    path: /modules/macymedcacheboost/redis
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostRedisController::index'
    methods: [GET, POST]

macymedcacheboost_memcached:
    path: /modules/macymedcacheboost/memcached
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostMemcachedController::index'
    methods: [GET, POST]

macymedcacheboost_invalidation:
    path: /modules/macymedcacheboost/invalidation
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostInvalidationController::index'
    methods: [GET, POST]

macymedcacheboost_warmer:
    path: /modules/macymedcacheboost/warmer
    controller: 'MacymedCacheBoost\Controller\Admin\AdminMacymedCacheBoostWarmerController::index'
    methods: [GET, POST]