# config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MacymedCacheBoost\Controller\Admin\:
        resource: '../../src/Controller/Admin/*'
        tags: ['controller.service_arguments']
        public: true

    MacymedCacheBoost\Services\:
        resource: '../../src/Services/*'
        public: true